import type { CapabilityCatalogueDocument } from "../types";

/** Program console — derived from the program nav + guarded routes. The Platforms
 *  group is the hand-off seam: opening a platform then defers to that platform's
 *  own catalogue (learning / bridge). */
export const programConsoleCatalogue: CapabilityCatalogueDocument = {
  schemaVersion: "1.0",
  documentType: "capability_catalogue",
  id: "program-console",
  name: "Program Console",
  description: "What a program role can be granted.",
  provider: { kind: "console", id: "program-console" },
  catalogueVersion: "1.0",
  capabilities: [
    { id: "program.offerings.create", label: "Create offerings", group: "offerings" },
    { id: "program.offerings.edit", label: "Edit offerings", group: "offerings" },
    { id: "program.offerings.publish", label: "Publish / close offerings", group: "offerings" },
    { id: "program.offerings.delete", label: "Delete offerings", group: "offerings" },
    { id: "program.appshells.manage", label: "Manage app shells", group: "appshells" },
    { id: "program.registrations.manage", label: "Manage registrations", group: "registrations" },
    { id: "program.people.manage", label: "Invite / remove members, assign roles", group: "people" },
    { id: "program.roles.manage", label: "Create / edit / delete custom roles", group: "people" },
    { id: "program.groups.manage", label: "Manage groups & participants", group: "people" },
    { id: "program.partners.manage", label: "Manage partner affiliations", group: "partners" },
    { id: "program.gates.manage", label: "Manage sign-in gates", group: "gates" },
    { id: "program.settings.branding", label: "Edit program branding", group: "settings" },
    { id: "program.community.participate", label: "Participate in community", group: "community" },
    { id: "program.platforms.open_learning", label: "Open the Learning platform", group: "platforms" },
    { id: "program.platforms.open_bridge", label: "Open the Bridge platform", group: "platforms" },
    { id: "program.platforms.open_appshells", label: "Open App Shells", group: "platforms" },
  ],
  resourceTypes: [],
  uiSurfaces: [
    { id: "overview", label: "Overview", kind: "navigation", group: "overview", routeOrComponent: "/", requiredAnyCapabilities: [] },
    { id: "offerings", label: "Offerings", kind: "navigation", group: "offerings", routeOrComponent: "/offerings", requiredAnyCapabilities: ["program.offerings.create", "program.offerings.edit"] },
    { id: "shells", label: "App Shells", kind: "navigation", group: "appshells", routeOrComponent: "/shells", requiredAnyCapabilities: ["program.appshells.manage", "program.platforms.open_appshells"] },
    { id: "registrations", label: "Registrations", kind: "navigation", group: "registrations", routeOrComponent: "/registrations", requiredAnyCapabilities: ["program.registrations.manage"] },
    { id: "groups", label: "Participants & Groups", kind: "navigation", group: "people", routeOrComponent: "/groups", requiredAnyCapabilities: ["program.groups.manage"] },
    { id: "community", label: "Community", kind: "navigation", group: "community", routeOrComponent: "/community", requiredAnyCapabilities: ["program.community.participate"] },
    { id: "team", label: "People", kind: "navigation", group: "people", routeOrComponent: "/team", requiredAnyCapabilities: ["program.people.manage", "program.roles.manage", "program.groups.manage"] },
    { id: "partners", label: "Partners", kind: "navigation", group: "partners", routeOrComponent: "/partners", requiredAnyCapabilities: ["program.partners.manage"] },
    { id: "gates", label: "Gates", kind: "navigation", group: "gates", routeOrComponent: "/gates", requiredAnyCapabilities: ["program.gates.manage"] },
    { id: "settings", label: "Settings", kind: "navigation", group: "settings", routeOrComponent: "/settings", requiredAnyCapabilities: ["program.settings.branding"] },
    { id: "learning", label: "Learning Platform", kind: "navigation", group: "platforms", routeOrComponent: "/learning", requiredAnyCapabilities: ["program.platforms.open_learning"] },
    { id: "bridge", label: "Bridge Platform", kind: "navigation", group: "platforms", routeOrComponent: "/bridge", requiredAnyCapabilities: ["program.platforms.open_bridge"] },
  ],
  groups: [
    { id: "offerings", label: "Offerings", order: 1, capabilityIds: ["program.offerings.create", "program.offerings.edit", "program.offerings.publish", "program.offerings.delete"], uiSurfaceIds: ["offerings"] },
    { id: "appshells", label: "App Shells", order: 2, capabilityIds: ["program.appshells.manage"], uiSurfaceIds: ["shells"] },
    { id: "registrations", label: "Registrations", order: 3, capabilityIds: ["program.registrations.manage"], uiSurfaceIds: ["registrations"] },
    { id: "people", label: "People", order: 4, capabilityIds: ["program.people.manage", "program.roles.manage", "program.groups.manage"], uiSurfaceIds: ["team", "groups"] },
    { id: "partners", label: "Partners", order: 5, capabilityIds: ["program.partners.manage"], uiSurfaceIds: ["partners"] },
    { id: "settings", label: "Settings", order: 6, capabilityIds: ["program.settings.branding"], uiSurfaceIds: ["settings"] },
    { id: "community", label: "Community", order: 7, capabilityIds: ["program.community.participate"], uiSurfaceIds: ["community"] },
    { id: "platforms", label: "Platforms", order: 8, capabilityIds: ["program.platforms.open_learning", "program.platforms.open_bridge", "program.platforms.open_appshells"], uiSurfaceIds: ["learning", "bridge", "shells"] },
    { id: "gates", label: "Gates", order: 9, capabilityIds: ["program.gates.manage"], uiSurfaceIds: ["gates"] },
  ],
  sampleRoleTemplates: [],
};
