/**
 * Zone 3 — Bridge implementation: Beginner 1 skill & concept taxonomy.
 * These IDs are the vocabulary shared by the evaluator, knowledge chunks,
 * and the learner model.
 */

export const CONCEPT_OPENING_BID = "CONCEPT_OPENING_BID";
export const CONCEPT_HCP = "CONCEPT_HCP";
export const CONCEPT_HAND_EVAL_BASIC = "CONCEPT_HAND_EVAL_BASIC";
export const CONCEPT_HAND_BALANCED = "CONCEPT_HAND_BALANCED";
export const CONCEPT_HAND_DISTRIBUTION = "CONCEPT_HAND_DISTRIBUTION";
export const CONCEPT_RESPONSE_1LEVEL = "CONCEPT_RESPONSE_1LEVEL";
export const CONCEPT_RAISE = "CONCEPT_RAISE";
export const CONCEPT_NT_RESPONSE = "CONCEPT_NT_RESPONSE";
export const CONCEPT_OPENER_REBID = "CONCEPT_OPENER_REBID";

export const CONCEPTS = {
  CONCEPT_OPENING_BID,
  CONCEPT_HCP,
  CONCEPT_HAND_EVAL_BASIC,
  CONCEPT_HAND_BALANCED,
  CONCEPT_HAND_DISTRIBUTION,
  CONCEPT_RESPONSE_1LEVEL,
  CONCEPT_RAISE,
  CONCEPT_NT_RESPONSE,
  CONCEPT_OPENER_REBID,
} as const;

export const SKILL_OPENING_1SUIT = "SKILL_OPENING_1SUIT";
export const SKILL_RESPONSE_NT = "SKILL_RESPONSE_NT";
export const SKILL_RESPONSE_1M_NT = "SKILL_RESPONSE_1M_NT";
export const SKILL_SIMPLE_RAISE = "SKILL_SIMPLE_RAISE";
export const SKILL_LIMIT_RAISE = "SKILL_LIMIT_RAISE";
export const SKILL_NEW_SUIT_1LEVEL = "SKILL_NEW_SUIT_1LEVEL";
export const SKILL_PASS_MINIMUM = "SKILL_PASS_MINIMUM";
export const SKILL_OPENER_REBID = "SKILL_OPENER_REBID";
export const SKILL_HCP_COUNTING = "SKILL_HCP_COUNTING";
export const SKILL_HAND_SHAPE = "SKILL_HAND_SHAPE";

export const SKILLS = {
  SKILL_OPENING_1SUIT,
  SKILL_RESPONSE_NT,
  SKILL_RESPONSE_1M_NT,
  SKILL_SIMPLE_RAISE,
  SKILL_LIMIT_RAISE,
  SKILL_NEW_SUIT_1LEVEL,
  SKILL_PASS_MINIMUM,
  SKILL_OPENER_REBID,
  SKILL_HCP_COUNTING,
  SKILL_HAND_SHAPE,
} as const;

export const BRIDGE_DOMAIN_ID = "bridge_gameplay";

// ---------------------------------------------------------------------------
// Card-play tactics (Watson, "The Play of the Hand at Bridge").
// Used by the card-play evaluator, scenarios, and knowledge package.
// ---------------------------------------------------------------------------

export const CONCEPT_PLAN_PLAY = "CONCEPT_PLAN_PLAY";
export const CONCEPT_FINESSE = "CONCEPT_FINESSE";
export const CONCEPT_TENACE = "CONCEPT_TENACE";
export const CONCEPT_ENTRIES = "CONCEPT_ENTRIES";
export const CONCEPT_HOLDUP = "CONCEPT_HOLDUP";
export const CONCEPT_DUCK = "CONCEPT_DUCK";
export const CONCEPT_ESTABLISH_SUIT = "CONCEPT_ESTABLISH_SUIT";
export const CONCEPT_DRAW_TRUMPS = "CONCEPT_DRAW_TRUMPS";
export const CONCEPT_RUFF = "CONCEPT_RUFF";
export const CONCEPT_OPENING_LEAD = "CONCEPT_OPENING_LEAD";
export const CONCEPT_RULE_OF_ELEVEN = "CONCEPT_RULE_OF_ELEVEN";
export const CONCEPT_THIRD_HAND_HIGH = "CONCEPT_THIRD_HAND_HIGH";
export const CONCEPT_SECOND_HAND_LOW = "CONCEPT_SECOND_HAND_LOW";
export const CONCEPT_COVER_HONOR = "CONCEPT_COVER_HONOR";
export const CONCEPT_SIGNALS = "CONCEPT_SIGNALS";
export const CONCEPT_COUNTING = "CONCEPT_COUNTING";

export const CARDPLAY_CONCEPTS = {
  CONCEPT_PLAN_PLAY,
  CONCEPT_FINESSE,
  CONCEPT_TENACE,
  CONCEPT_ENTRIES,
  CONCEPT_HOLDUP,
  CONCEPT_DUCK,
  CONCEPT_ESTABLISH_SUIT,
  CONCEPT_DRAW_TRUMPS,
  CONCEPT_RUFF,
  CONCEPT_OPENING_LEAD,
  CONCEPT_RULE_OF_ELEVEN,
  CONCEPT_THIRD_HAND_HIGH,
  CONCEPT_SECOND_HAND_LOW,
  CONCEPT_COVER_HONOR,
  CONCEPT_SIGNALS,
  CONCEPT_COUNTING,
} as const;

export const SKILL_PLAN_TRICKS = "SKILL_PLAN_TRICKS";
export const SKILL_TAKE_FINESSE = "SKILL_TAKE_FINESSE";
export const SKILL_MANAGE_ENTRIES = "SKILL_MANAGE_ENTRIES";
export const SKILL_HOLDUP_PLAY = "SKILL_HOLDUP_PLAY";
export const SKILL_DUCK_PLAY = "SKILL_DUCK_PLAY";
export const SKILL_ESTABLISH_LONG_SUIT = "SKILL_ESTABLISH_LONG_SUIT";
export const SKILL_DRAW_TRUMPS = "SKILL_DRAW_TRUMPS";
export const SKILL_RUFF_IN_DUMMY = "SKILL_RUFF_IN_DUMMY";
export const SKILL_OPENING_LEAD_NT = "SKILL_OPENING_LEAD_NT";
export const SKILL_OPENING_LEAD_SUIT = "SKILL_OPENING_LEAD_SUIT";
export const SKILL_RULE_OF_ELEVEN = "SKILL_RULE_OF_ELEVEN";
export const SKILL_THIRD_HAND_HIGH = "SKILL_THIRD_HAND_HIGH";
export const SKILL_SECOND_HAND_LOW = "SKILL_SECOND_HAND_LOW";
export const SKILL_COVER_HONOR = "SKILL_COVER_HONOR";
export const SKILL_DEFENSIVE_SIGNAL = "SKILL_DEFENSIVE_SIGNAL";

export const CARDPLAY_SKILLS = {
  SKILL_PLAN_TRICKS,
  SKILL_TAKE_FINESSE,
  SKILL_MANAGE_ENTRIES,
  SKILL_HOLDUP_PLAY,
  SKILL_DUCK_PLAY,
  SKILL_ESTABLISH_LONG_SUIT,
  SKILL_DRAW_TRUMPS,
  SKILL_RUFF_IN_DUMMY,
  SKILL_OPENING_LEAD_NT,
  SKILL_OPENING_LEAD_SUIT,
  SKILL_RULE_OF_ELEVEN,
  SKILL_THIRD_HAND_HIGH,
  SKILL_SECOND_HAND_LOW,
  SKILL_COVER_HONOR,
  SKILL_DEFENSIVE_SIGNAL,
} as const;
