export default function BoardsPage() {
  return (
    <div className="mx-auto max-w-4xl space-y-3">
      <h1 className="text-2xl font-semibold tracking-tight">Boards & Deals</h1>
      <p className="text-sm text-neutral-600">
        Random deals, saved boards, PBN/LIN imports, and level-scoped practice
        sets generated by the constrained dealer (e.g. Level 1 sets where no
        seat&apos;s systemic action is 1NT). Dealer lands in Phase 6; import
        formats in Phase 2.
      </p>
    </div>
  );
}
