// The competitive seat (SAYC booklet ch. 7–8): overcalls, takeout doubles
// and their advances (including the cue-bid via the contextual bid_suit
// action), negative doubles, Michaels and the Unusual 2NT, weak jump
// overcalls, Jordan 2NT, the 10+ redouble, and balancing — the last two
// finally expressible with LHO in the auction memory.

import {
  aces,
  all,
  any,
  anyBid,
  auctionItem,
  bal,
  bid,
  bidAt,
  bidLongest,
  bidSuit,
  ctx,
  dbl,
  hcp,
  is,
  len,
  low,
  high,
  passed,
  quality,
  range,
  rdbl,
  rule,
  stopper,
  toggle,
  tp,
  type TemplateItem,
} from "../dsl";

const THEIR_ONE_LEVEL = bidAt({ level: 1, strains: ["C", "D", "H", "S"] });

export const COMPETITIVE: TemplateItem[] = [
  auctionItem(
    "overcalls",
    "Simple overcalls",
    "Overcall a good five-card suit: 8–16 HCP at the one level, 11–16 with a good suit at the two level. Quality matters more than points.",
    "agreement",
    [
      rule(
        "one-level",
        "One-level overcall",
        ctx("overcaller", { rhoLast: THEIR_ONE_LEVEL }),
        all(
          hcp(low("overcall_range"), high("overcall_range")),
          len("own_longest_suit", 5),
          any(quality("own_longest_suit"), quality("own_longest_suit", "three_of_top_five")),
        ),
        bidLongest(["S", "H", "D", "C"], 1),
        40,
      ),
      rule(
        "two-level",
        "Two-level overcall",
        ctx("overcaller", { rhoLast: anyBid }),
        all(hcp(11, high("overcall_range")), len("own_longest_suit", 5), any(quality("own_longest_suit"), quality("own_longest_suit", "three_of_top_five"))),
        bidLongest(["S", "H", "D", "C"], 2),
        41,
      ),
    ],
    {
      settings: [range("overcall_range", "Simple overcall range (HCP)", 8, 16, { min: 6, max: 18 })],
    },
  ),

  auctionItem(
    "nt-overcall",
    "1NT overcall",
    "A direct 1NT overcall shows 15–18 balanced with a stopper in their suit. Advancer's only conventional response is 2♣ Stayman; everything else is natural.",
    "agreement",
    [
      rule(
        "overcall",
        "1NT overcall",
        ctx("overcaller", { rhoLast: THEIR_ONE_LEVEL }),
        all(bal(), hcp(15, 18), stopper("rho_bid_suit")),
        bid(1, "N"),
        39,
      ),
      rule(
        "stayman-advance",
        "2♣ Stayman by advancer",
        ctx("advancer", { partnerLast: is("1N"), contested: true }),
        all(hcp(8), any(len("S", 4), len("H", 4))),
        bid(2, "C"),
        40,
      ),
      rule(
        "stayman-reply-h",
        "Show four hearts (over the advance)",
        ctx("overcaller", { ownLast: is("1N"), partnerLast: is("2C") }),
        len("H", 4),
        bid(2, "H"),
        41,
      ),
      rule(
        "stayman-reply-s",
        "Show four spades (over the advance)",
        ctx("overcaller", { ownLast: is("1N"), partnerLast: is("2C") }),
        len("S", 4),
        bid(2, "S"),
        42,
      ),
      rule(
        "stayman-reply-d",
        "Deny a major (over the advance)",
        ctx("overcaller", { ownLast: is("1N"), partnerLast: is("2C") }),
        { all: [] },
        bid(2, "D"),
        43,
      ),
    ],
  ),

  auctionItem(
    "takeout-double",
    "Takeout doubles",
    "Double is for takeout over any opening partscore bid (through 4♦), with opening values and shortness in their suit (or 17+ with any shape); a double of a game-level opening (4♥ or higher) is penalty. Partner MUST advance: cheapest suit with a weak hand, a JUMP with invitational values (9–11), and a cue-bid of their suit as the game force.",
    "convention",
    [
      rule(
        "double",
        "Takeout double",
        ctx("overcaller", { rhoLast: bidAt({ max: 2, strains: ["C", "D", "H", "S"] }) }),
        any(all(hcp(12), len("rho_bid_suit", undefined, 2)), hcp(17)),
        dbl,
        30,
      ),
      rule(
        "double-preempt",
        "Takeout double of a preempt (through 4♦)",
        ctx("overcaller", { rhoLast: bidAt({ min: 3, max: 3, strains: ["C", "D", "H", "S"] }) }),
        all(hcp(13), len("rho_bid_suit", undefined, 2)),
        dbl,
        31,
      ),
      rule(
        "double-4m",
        "Takeout double of 4♣/4♦",
        ctx("overcaller", { rhoLast: bidAt({ level: 4, strains: ["C", "D"] }) }),
        all(hcp(13), len("rho_bid_suit", undefined, 2)),
        dbl,
        32,
      ),
      rule(
        "advance-cue",
        "Advance with a cue-bid (12+)",
        ctx("advancer", { partnerLast: { kind: "double" } }),
        tp(12),
        bidSuit("lho_bid_suit"),
        33,
      ),
      rule(
        "advance-jump",
        "Invitational jump advance (9–11)",
        ctx("advancer", { partnerLast: { kind: "double" }, lhoLast: bidAt({ level: 1 }) }),
        all(tp(9, 11), any(len("S", 4), len("H", 4), len("D", 4), len("C", 4))),
        bidLongest(["S", "H", "D", "C"], 2),
        34,
      ),
      rule(
        "advance",
        "Advance to the cheapest suit",
        ctx("advancer", { partnerLast: { kind: "double" } }),
        { all: [] },
        bidLongest(["S", "H", "D", "C"]),
        35,
      ),
      rule(
        "penalty-game-double",
        "Penalty double of a game-level opening",
        ctx("overcaller", { rhoLast: bidAt({ min: 4, strains: ["H", "S"] }) }),
        all(hcp(13), { aces: { min: 1 } }),
        dbl,
        36,
      ),
    ],
    { settings: [toggle("takeout_dbl_on", "Takeout doubles")], sets: ["conventions"] },
  ),

  auctionItem(
    "negative-double",
    "Negative doubles",
    "When partner opens and RHO overcalls (through 2♠), double is for takeout: over their 1♦ it shows both majors (4–4 or better); over 1♥ it shows EXACTLY four spades (1♠ would promise five); over 1♠ it shows four-plus hearts. Bidding a new major at the two level instead shows 11+ points and five-plus cards.",
    "convention",
    [
      // Booklet: 1♦–(1♥)–1♠ promises FIVE spades; the double shows four.
      rule(
        "five-spades",
        "Bid 1♠ with five spades instead",
        ctx("responder", { contested: true, rhoLast: is("1H") }),
        all(hcp(6), len("S", 5)),
        bid(1, "S"),
        35,
      ),
      rule(
        "double-vs-1d",
        "Negative double of 1♦ (both majors)",
        ctx("responder", { contested: true, rhoLast: is("1D") }),
        all(hcp(6), len("S", 4), len("H", 4)),
        dbl,
        36,
      ),
      rule(
        "double-vs-1h",
        "Negative double of 1♥ (exactly four spades)",
        ctx("responder", { contested: true, rhoLast: is("1H") }),
        all(hcp(6), len("S", 4, 4)),
        dbl,
        37,
      ),
      rule(
        "double-vs-1s",
        "Negative double of 1♠ (four-plus hearts)",
        ctx("responder", { contested: true, rhoLast: is("1S") }),
        all(hcp(6), len("H", 4)),
        dbl,
        38,
      ),
      rule(
        "double-generic",
        "Negative double (two-level overcalls)",
        ctx("responder", { contested: true, rhoLast: bidAt({ level: 2, strains: ["C", "D", "H", "S"] }) }),
        all(hcp(8), any(len("S", 4), len("H", 4))),
        dbl,
        39,
      ),
      rule(
        "two-level-major",
        "New major at the two level (11+, five cards)",
        ctx("responder", { contested: true, rhoLast: bidAt({ max: 2, strains: ["C", "D", "H", "S"] }) }),
        all(tp(11), any(len("S", 5), len("H", 5))),
        { type: "bid_longest", among: ["S", "H"], level: 2 },
        40,
      ),
    ],
    { settings: [toggle("neg_dbl_on", "Negative doubles")], sets: ["conventions"] },
  ),

  auctionItem(
    "michaels",
    "Michaels cue-bid",
    "A direct cue-bid of their opening shows five-five: both majors over a minor, the other major plus a minor over a major. The cue is Michaels only while the opponents have shown ONE suit — after they bid two, a cue-bid is natural. After Michaels over a MAJOR, advancer's 2NT asks for the unspecified minor and the cue-bidder answers 3♣ or 3♦.",
    "convention",
    [
      rule(
        "over-minor",
        "Michaels over a minor",
        ctx("overcaller", { rhoLast: bidAt({ level: 1, strains: ["C", "D"] }), oppSuitsBidMax: 1 }),
        all(len("S", 5), len("H", 5), hcp(8)),
        bidSuit("rho_bid_suit"),
        25,
      ),
      rule(
        "over-hearts",
        "Michaels over 1♥",
        ctx("overcaller", { rhoLast: is("1H"), oppSuitsBidMax: 1 }),
        all(len("S", 5), any(len("C", 5), len("D", 5)), hcp(8)),
        bidSuit("rho_bid_suit"),
        26,
      ),
      rule(
        "over-spades",
        "Michaels over 1♠",
        ctx("overcaller", { rhoLast: is("1S"), oppSuitsBidMax: 1 }),
        all(len("H", 5), any(len("C", 5), len("D", 5)), hcp(8)),
        bidSuit("rho_bid_suit"),
        27,
      ),
      rule(
        "minor-ask",
        "2NT asks for the Michaels minor",
        ctx("advancer", {
          partnerCued: true,
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        all(len("H", 0, 2), len("S", 0, 2)),
        bid(2, "N"),
        28,
      ),
      rule(
        "minor-reply",
        "Show the minor over the 2NT ask",
        ctx("overcaller", {
          ownLast: bidAt({ level: 2, strains: ["H", "S"] }),
          partnerLast: is("2N"),
        }),
        any(len("C", 5), len("D", 5)),
        bidLongest(["C", "D"], 3),
        29,
      ),
    ],
    { settings: [toggle("michaels_on", "Michaels cue-bid")], sets: ["conventions"] },
  ),

  auctionItem(
    "penalty-redouble",
    "Penalty redouble at the four level",
    "When your side reaches the four level or higher and the opponents double, a redouble is TO PLAY — pure confidence, raising the stakes. This rule is OFF by default: the machine cannot yet judge combined confidence, so an expert should calibrate the conditions (currently: the redoubler holds 16+ HCP with two aces) before enabling it.",
    "convention",
    [
      rule(
        "business",
        "Business redouble of their double",
        ctx("any", {
          ownLast: bidAt({ min: 4, strains: ["C", "D", "H", "S"] }),
          rhoLast: { kind: "double" },
        }),
        all(hcp(16), aces(2)),
        rdbl,
        30,
      ),
    ],
    { settings: [toggle("rdbl_4plus_on", "Business redouble (4-level+)", false)], sets: ["conventions"] },
  ),

  auctionItem(
    "unusual-2nt",
    "Unusual 2NT",
    "A jump overcall of 2NT shows at least 5–5 in the LOWEST TWO UNBID suits: both minors over a major opening, clubs and hearts over 1♦, diamonds and hearts over 1♣.",
    "convention",
    [
      rule(
        "jump",
        "Unusual 2NT over a major (both minors)",
        ctx("overcaller", { rhoLast: bidAt({ level: 1, strains: ["H", "S"] }) }),
        all(len("C", 5), len("D", 5), hcp(6)),
        bid(2, "N"),
        28,
      ),
      rule(
        "jump-1d",
        "Unusual 2NT over 1♦ (clubs + hearts)",
        ctx("overcaller", { rhoLast: is("1D") }),
        all(len("C", 5), len("H", 5), hcp(6)),
        bid(2, "N"),
        29,
      ),
      rule(
        "jump-1c",
        "Unusual 2NT over 1♣ (diamonds + hearts)",
        ctx("overcaller", { rhoLast: is("1C") }),
        all(len("D", 5), len("H", 5), hcp(6)),
        bid(2, "N"),
        30,
      ),
    ],
    { settings: [toggle("unt_on", "Unusual 2NT")], sets: ["conventions"] },
  ),

  auctionItem(
    "weak-jump-overcall",
    "Weak jump overcalls",
    "A jump overcall is preemptive — a good six-card suit with 5–10 HCP, like a weak two.",
    "convention",
    [
      rule(
        "jump",
        "Weak jump overcall",
        ctx("overcaller", { rhoLast: THEIR_ONE_LEVEL }),
        all(hcp(5, 10), len("own_longest_suit", 6), any(quality("own_longest_suit"), quality("own_longest_suit", "three_of_top_five"))),
        bidLongest(["S", "H", "D"], 2),
        29,
      ),
    ],
    { settings: [toggle("wjo_on", "Weak jump overcalls")], sets: ["conventions"] },
  ),

  auctionItem(
    "jordan-2nt",
    "Jordan 2NT and the 10+ redouble",
    "When partner's opening is doubled for takeout: 2NT shows a limit raise or better with support (Jordan); redouble shows 10+ points (though a descriptive bid is usually better); a jump shift is weak and preemptive — a six-plus card suit, like a weak two-bid; a raise is preemptive.",
    "convention",
    [
      rule(
        "jordan",
        "Jordan 2NT",
        ctx("responder", { rhoLast: { kind: "double" } }),
        all(len("partner_last_bid_suit", 3), tp(10)),
        bid(2, "N"),
        33,
      ),
      rule(
        "redouble",
        "Redouble (10+)",
        ctx("responder", { rhoLast: { kind: "double" } }),
        all(hcp(10), len("partner_last_bid_suit", undefined, 2)),
        rdbl,
        34,
      ),
      rule(
        "weak-jump",
        "Weak jump response over the double",
        ctx("responder", { rhoLast: { kind: "double" } }),
        all(hcp(undefined, 9), len("own_longest_suit", 6)),
        { type: "bid_longest", among: ["S", "H", "D", "C"], level: 2 },
        35,
      ),
    ],
    { settings: [toggle("jordan_on", "Jordan 2NT over doubles")], sets: ["conventions"] },
  ),

  auctionItem(
    "cue-bid-raise",
    "Cue-bid raise by advancer",
    "After partner overcalls, the ONLY forcing advance is a cue-bid of opener's suit — it asks about the quality of the overcall (and usually shows a good raise, 11+). Overcaller rebids the suit with a minimum; any other bid shows extra strength. A direct raise is merely competitive.",
    "agreement",
    [
      rule(
        "cue",
        "Cue-bid the good raise",
        ctx("advancer", { partnerLast: anyBid, lhoLast: anyBid }),
        all(len("partner_last_bid_suit", 3), tp(11)),
        bidSuit("lho_bid_suit"),
        36,
      ),
      rule(
        "quality-reply-min",
        "Minimum overcall — rebid the suit",
        ctx("overcaller", { ownFirst: bidAt({ level: 1, strains: ["C", "D", "H", "S"] }), partnerLast: bidAt({ max: 3 }), roundMin: 2, contested: true }),
        all(tp(undefined, 11), len("own_first_bid_suit", 5)),
        bidSuit("own_first_bid_suit"),
        38,
      ),
      rule(
        "quality-reply-extra",
        "Extra strength — bid beyond the suit",
        ctx("overcaller", { ownFirst: bidAt({ level: 1, strains: ["C", "D", "H", "S"] }), partnerLast: bidAt({ max: 3 }), roundMin: 2, contested: true }),
        all(tp(12), bal()),
        bid(2, "N"),
        39,
      ),
      rule(
        "raise",
        "Competitive raise",
        ctx("advancer", { partnerLast: bidAt({ max: 2, strains: ["C", "D", "H", "S"] }) }),
        all(len("partner_last_bid_suit", 3), tp(6, 10)),
        { type: "raise_partner", toLevel: 2 },
        37,
      ),
    ],
  ),

  auctionItem(
    "balancing",
    "Balancing",
    "In the pass-out seat, compete with less than a direct action would need: a reopening double is takeout from about 9 points, and a balancing 1NT shows 10–15 with a stopper. A reopening bid means much the same as a direct-seat bid, a king lighter.",
    "agreement",
    [
      rule(
        "balance-nt",
        "Balancing 1NT",
        ctx("overcaller", { rhoLast: passed, lhoLast: THEIR_ONE_LEVEL, partnerLast: passed }),
        all(bal(), hcp(10, 15), stopper("lho_bid_suit")),
        bid(1, "N"),
        50,
      ),
      rule(
        "balance-double",
        "Reopening takeout double",
        ctx("overcaller", { rhoLast: passed, lhoLast: THEIR_ONE_LEVEL, partnerLast: passed }),
        all(hcp(9), len("lho_bid_suit", undefined, 2)),
        dbl,
        49,
      ),
      rule(
        "balance-suit",
        "Balancing overcall",
        ctx("overcaller", { rhoLast: passed, lhoLast: THEIR_ONE_LEVEL, partnerLast: passed }),
        all(hcp(8), len("own_longest_suit", 5)),
        bidLongest(["S", "H", "D", "C"]),
        51,
      ),
    ],
  ),
];
