// Responding to notrump (SAYC booklet ch. 2, full pass 2026-07-21):
// Stayman with every opener reply and responder continuation, Jacoby + Texas
// transfers, the 2♠ minor-suit signoff relay, invitational 3♣/3♦, slam-try
// 3♥/3♠, Gerber with the 5♣ king ask, the quantitative ladder — and the
// booklet's interference policy (systems ON over a double, OFF over a bid;
// a cue-bid substitutes for Stayman over their overcall). The same systems
// apply after a 2♣–2♦–2NT start.

import {
  all,
  any,
  anyBid,
  auctionItem,
  bal,
  bid,
  bidAt,
  bidSuit,
  ctx,
  hcp,
  is,
  len,
  not,
  overPassOrDouble,
  pass as passAction,
  raise,
  rule,
  toggle,
  tp,
  type TemplateItem,
} from "../dsl";

const NT_OPENING = bidAt({ max: 2, strains: ["N"] });
/** After 2♣ – 2♦ – 2NT the notrump systems apply as over a 2NT opening. */
const AFTER_2C_2NT = { opening: is("2C"), ownLast: is("2D"), partnerLast: is("2N") } as const;

export const NT_RESPONSES: TemplateItem[] = [
  auctionItem(
    "stayman",
    "Stayman",
    "Over partner's 1NT (or 2NT), 2♣ (3♣) asks for a four-card major with invitational values or better — NON-forcing Stayman: the auction may stop in two of a suit. Opener rebids 2♥ with 4–4 in the majors and denies with 2♦. If responder rebids three of either minor, that shows slam interest and a five-card or longer suit. Stayman stays on over an opponent's double and switches off over a bid — with game-forcing values, a cue-bid of their suit takes its place. The same ask applies after 2♣–2♦–2NT (3♣) and over a 3NT opening (4♣ when not Gerber).",
    "convention",
    [
      // The asks (on over a double, off over a bid).
      ...overPassOrDouble(
        rule(
          "ask",
          "Stayman 2♣ ask",
          ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
          all(hcp(8), any(len("S", 4), len("H", 4))),
          bid(2, "C"),
          25,
        ),
      ),
      ...overPassOrDouble(
        rule(
          "ask2n",
          "Stayman 3♣ over 2NT",
          ctx("responder", { opening: is("2N"), partnerLast: is("2N") }),
          all(hcp(4), any(len("S", 4), len("H", 4))),
          bid(3, "C"),
          26,
        ),
      ),
      rule(
        "ask-3n",
        "4♣ Stayman over a 3NT opening",
        ctx("responder", { opening: is("3N"), partnerLast: is("3N"), contested: false }),
        any(len("S", 4), len("H", 4)),
        bid(4, "C"),
        24,
      ),
      rule(
        "reply-h-3n",
        "Show four hearts (over 3NT)",
        ctx("opener", { ownFirst: is("3N"), partnerLast: is("4C") }),
        len("H", 4),
        bid(4, "H"),
        23,
      ),
      rule(
        "reply-s-3n",
        "Show four spades (over 3NT)",
        ctx("opener", { ownFirst: is("3N"), partnerLast: is("4C") }),
        len("S", 4),
        bid(4, "S"),
        23,
      ),
      rule(
        "ask-2c",
        "Stayman 3♣ after 2♣–2♦–2NT",
        ctx("responder", { ...AFTER_2C_2NT }),
        any(len("S", 4), len("H", 4)),
        bid(3, "C"),
        27,
      ),
      // Responder's 3♣/3♦ REBID after the reply: slam interest, 5+ minor.
      rule(
        "cont-minor-slam-c",
        "3♣ rebid — slam interest, five clubs",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: bidAt({ level: 2 }) }),
        all(len("C", 5), tp(14)),
        bid(3, "C"),
        33,
      ),
      rule(
        "cont-minor-slam-d",
        "3♦ rebid — slam interest, five diamonds",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: bidAt({ level: 2 }) }),
        all(len("D", 5), tp(14)),
        bid(3, "D"),
        34,
      ),
      // Their overcall killed the systems: cue-bid = Stayman with game force.
      rule(
        "cue-as-stayman",
        "Cue-bid replaces Stayman over their bid",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), rhoLast: anyBid, contested: true }),
        all(hcp(10), any(len("S", 4), len("H", 4))),
        bidSuit("rho_bid_suit"),
        28,
      ),
      // Opener's replies (hearts first with both).
      rule(
        "reply-h",
        "Show four hearts",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2C") }),
        len("H", 4),
        bid(2, "H"),
        29,
      ),
      rule(
        "reply-s",
        "Show four spades",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2C") }),
        len("S", 4),
        bid(2, "S"),
        30,
      ),
      rule(
        "reply-d",
        "Deny a four-card major",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2C") }),
        { all: [] },
        bid(2, "D"),
        31,
      ),
      rule(
        "reply-h-2n",
        "Show four hearts (over a 3♣ ask)",
        ctx("opener", { ownLast: bidAt({ level: 2, strains: ["N"] }), partnerLast: is("3C") }),
        len("H", 4),
        bid(3, "H"),
        32,
      ),
      rule(
        "reply-s-2n",
        "Show four spades (over a 3♣ ask)",
        ctx("opener", { ownLast: bidAt({ level: 2, strains: ["N"] }), partnerLast: is("3C") }),
        len("S", 4),
        bid(3, "S"),
        33,
      ),
      rule(
        "reply-d-2n",
        "Deny a major (over a 3♣ ask)",
        ctx("opener", { ownLast: bidAt({ level: 2, strains: ["N"] }), partnerLast: is("3C") }),
        { all: [] },
        bid(3, "D"),
        34,
      ),
      // Responder's continuations after a 2♦ denial.
      rule(
        "cont-2n",
        "Invite after the denial",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: is("2D") }),
        hcp(8, 9),
        bid(2, "N"),
        35,
      ),
      rule(
        "cont-3n",
        "Bid game after the denial",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: is("2D") }),
        hcp(10, 15),
        bid(3, "N"),
        36,
      ),
      // Continuations when opener shows a major.
      rule(
        "cont-raise-inv",
        "Invite with the fit",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: bidAt({ level: 2, strains: ["H", "S"] }) }),
        all(hcp(8, 9), len("partner_last_bid_suit", 4)),
        raise(3),
        37,
      ),
      rule(
        "cont-raise-game",
        "Bid game in the fit",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: bidAt({ level: 2, strains: ["H", "S"] }) }),
        all(hcp(10, 15), len("partner_last_bid_suit", 4)),
        raise(4),
        38,
      ),
      rule(
        "cont-3n-nofit",
        "3NT without the fit",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: bidAt({ level: 2, strains: ["H", "S"] }) }),
        all(hcp(10, 15), len("partner_last_bid_suit", undefined, 3)),
        bid(3, "N"),
        39,
      ),
    ],
    { settings: [toggle("stayman_on", "Stayman")], sets: ["conventions"] },
  ),

  auctionItem(
    "jacoby-transfers",
    "Jacoby transfers",
    "Over partner's notrump opening, 2♦ shows five-plus hearts and 2♥ shows five-plus spades (3♦/3♥ over 2NT and after 2♣–2♦–2NT). Opener completes — jumping with four-card support and 17 — and responder passes, invites, or drives to game. Transfers stay on over a double and switch off over a bid.",
    "convention",
    [
      ...overPassOrDouble(
        rule(
          "xfer-h",
          "Transfer to hearts",
          ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
          len("H", 5),
          bid(2, "D"),
          15,
        ),
      ),
      ...overPassOrDouble(
        rule(
          "xfer-s",
          "Transfer to spades",
          ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
          len("S", 5),
          bid(2, "H"),
          16,
        ),
      ),
      ...overPassOrDouble(
        rule(
          "xfer-h-2n",
          "Transfer to hearts (over 2NT)",
          ctx("responder", { opening: is("2N"), partnerLast: is("2N") }),
          len("H", 5),
          bid(3, "D"),
          17,
        ),
      ),
      ...overPassOrDouble(
        rule(
          "xfer-s-2n",
          "Transfer to spades (over 2NT)",
          ctx("responder", { opening: is("2N"), partnerLast: is("2N") }),
          len("S", 5),
          bid(3, "H"),
          18,
        ),
      ),
      rule(
        "xfer-h-3n",
        "4♦ transfer to hearts (over 3NT)",
        ctx("responder", { opening: is("3N"), partnerLast: is("3N"), contested: false }),
        len("H", 5),
        bid(4, "D"),
        21,
      ),
      rule(
        "xfer-s-3n",
        "4♥ transfer to spades (over 3NT)",
        ctx("responder", { opening: is("3N"), partnerLast: is("3N"), contested: false }),
        len("S", 5),
        bid(4, "H"),
        22,
      ),
      rule(
        "complete-h-4",
        "Complete the 4♦ transfer",
        ctx("opener", { ownFirst: is("3N"), partnerLast: is("4D") }),
        { all: [] },
        bid(4, "H"),
        29,
      ),
      rule(
        "complete-s-4",
        "Complete the 4♥ transfer",
        ctx("opener", { ownFirst: is("3N"), partnerLast: is("4H") }),
        { all: [] },
        bid(4, "S"),
        30,
      ),
      rule(
        "xfer-h-2c",
        "Transfer to hearts (after 2♣–2♦–2NT)",
        ctx("responder", { ...AFTER_2C_2NT }),
        len("H", 5),
        bid(3, "D"),
        19,
      ),
      rule(
        "xfer-s-2c",
        "Transfer to spades (after 2♣–2♦–2NT)",
        ctx("responder", { ...AFTER_2C_2NT }),
        len("S", 5),
        bid(3, "H"),
        20,
      ),
      // Opener: super-accept with four trumps and a maximum, else complete.
      rule(
        "super-h",
        "Super-accept hearts",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2D") }),
        all(len("H", 4), hcp(17)),
        bid(3, "H"),
        21,
      ),
      rule(
        "super-s",
        "Super-accept spades",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2H") }),
        all(len("S", 4), hcp(17)),
        bid(3, "S"),
        22,
      ),
      rule(
        "complete-h",
        "Complete the hearts transfer",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2D") }),
        { all: [] },
        bid(2, "H"),
        23,
      ),
      rule(
        "complete-s",
        "Complete the spades transfer",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2H") }),
        { all: [] },
        bid(2, "S"),
        24,
      ),
      rule(
        "complete-h-3",
        "Complete at the three level",
        ctx("opener", { ownLast: bidAt({ level: 2, strains: ["N"] }), partnerLast: is("3D") }),
        { all: [] },
        bid(3, "H"),
        25,
      ),
      rule(
        "complete-s-3",
        "Complete at the three level",
        ctx("opener", { ownLast: bidAt({ level: 2, strains: ["N"] }), partnerLast: is("3H") }),
        { all: [] },
        bid(3, "S"),
        26,
      ),
      // Responder's continuations (generic across both majors).
      rule(
        "cont-pass",
        "Pass with a weak hand",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        tp(undefined, 8),
        passAction,
        40,
      ),
      rule(
        "cont-invite-nt",
        "Invite with 2NT (five-card suit)",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        all(hcp(8, 9), len("partner_last_bid_suit", undefined, 5)),
        bid(2, "N"),
        41,
      ),
      rule(
        "cont-invite-raise",
        "Invite with the six-card suit",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        all(hcp(8, 9), len("partner_last_bid_suit", 6)),
        raise(3),
        42,
      ),
      rule(
        "cont-game-nt",
        "3NT with five and game values",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        all(hcp(10, 15), len("partner_last_bid_suit", 5, 5)),
        bid(3, "N"),
        43,
      ),
      rule(
        "cont-game-raise",
        "Game with six-plus trumps",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        all(hcp(10, 15), len("partner_last_bid_suit", 6)),
        raise(4),
        44,
      ),
      // Opener corrects 3NT to four of the major with three-card support.
      rule(
        "correct-h",
        "Correct 3NT to 4♥",
        ctx("opener", { ownFirst: is("1N"), partnerFirst: is("2D"), partnerLast: is("3N") }),
        len("H", 3),
        bid(4, "H"),
        45,
      ),
      rule(
        "correct-s",
        "Correct 3NT to 4♠",
        ctx("opener", { ownFirst: is("1N"), partnerFirst: is("2H"), partnerLast: is("3N") }),
        len("S", 3),
        bid(4, "S"),
        46,
      ),
    ],
    { settings: [toggle("jacoby_on", "Jacoby transfers")], sets: ["conventions"] },
  ),

  auctionItem(
    "minor-signoff",
    "2♠ minor-suit signoff over 1NT",
    "With a weak hand and a long minor, respond 2♠: opener must rebid 3♣, which responder passes with clubs or corrects to 3♦ with diamonds.",
    "convention",
    [
      rule(
        "relay",
        "2♠ with a weak long minor",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), rhoLast: { kind: "pass" } }),
        all(hcp(undefined, 7), any(len("C", 6), len("D", 6))),
        bid(2, "S"),
        17,
      ),
      rule(
        "forced-3c",
        "Forced 3♣ rebid",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2S") }),
        { all: [] },
        bid(3, "C"),
        18,
      ),
      rule(
        "correct-3d",
        "Correct to 3♦ (diamond bust)",
        ctx("responder", { opening: is("1N"), ownLast: is("2S"), partnerLast: is("3C") }),
        len("D", 6),
        bid(3, "D"),
        19,
      ),
      rule(
        "pass-3c",
        "Pass with the club bust",
        ctx("responder", { opening: is("1N"), ownLast: is("2S"), partnerLast: is("3C") }),
        { all: [] },
        passAction,
        20,
      ),
    ],
    { settings: [toggle("minor_signoff_on", "2♠ minor signoff")], sets: ["conventions"] },
  ),

  auctionItem(
    "nt-invitational-minors",
    "Invitational 3♣/3♦ over 1NT",
    "A direct 3♣/3♦ over 1NT shows a six-card or longer minor and invites 3NT; a direct 3♥/3♠ shows a six-card major with slam interest (with only game values, transfer instead).",
    "agreement",
    [
      rule(
        "inv-c",
        "3♣ invitational",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        all(len("C", 6), hcp(8, 9)),
        bid(3, "C"),
        43,
      ),
      rule(
        "inv-d",
        "3♦ invitational",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        all(len("D", 6), hcp(8, 9)),
        bid(3, "D"),
        44,
      ),
      rule(
        "slam-try-h",
        "3♥ slam try (six-card suit)",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        all(len("H", 6), tp(16)),
        bid(3, "H"),
        45,
      ),
      rule(
        "slam-try-s",
        "3♠ slam try (six-card suit)",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        all(len("S", 6), tp(16)),
        bid(3, "S"),
        46,
      ),
    ],
  ),

  auctionItem(
    "texas-transfers",
    "Texas transfers",
    "Over 1NT with a six-card major and game values, 4♦ transfers to 4♥ and 4♥ transfers to 4♠. On over a double, off over a bid.",
    "convention",
    [
      ...overPassOrDouble(
        rule(
          "tx-h",
          "Texas transfer to hearts",
          ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
          all(len("H", 6), hcp(10, 15)),
          bid(4, "D"),
          13,
        ),
      ),
      ...overPassOrDouble(
        rule(
          "tx-s",
          "Texas transfer to spades",
          ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
          all(len("S", 6), hcp(10, 15)),
          bid(4, "H"),
          14,
        ),
      ),
      rule(
        "tx-complete-h",
        "Complete to 4♥",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("4D") }),
        { all: [] },
        bid(4, "H"),
        15,
      ),
      rule(
        "tx-complete-s",
        "Complete to 4♠",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("4H") }),
        { all: [] },
        bid(4, "S"),
        16,
      ),
    ],
    { settings: [toggle("texas_on", "Texas transfers")], sets: ["conventions"] },
  ),

  auctionItem(
    "gerber",
    "Gerber over notrump",
    "4♣ is Gerber over ANY 1NT or 2NT by partner — openings AND rebids. Responses show aces by steps: 4♦ = 0 or 4, 4♥ = 1, 4♠ = 2, 4NT = 3. A 5♣ continuation asks kings the same way (and guarantees the partnership holds all the aces); ANY other continuation by the Gerber bidder — including 4NT — is to play.",
    "convention",
    [
      rule(
        "ask",
        "Gerber 4♣ ask",
        ctx("responder", { opening: NT_OPENING, partnerLast: NT_OPENING }),
        all(tp(18), not(any(len("S", 4), len("H", 4)))),
        bid(4, "C"),
        12,
      ),
      // The booklet: 4♣ is Gerber over ANY 1NT/2NT by partner, including
      // REBIDS of 1NT/2NT.
      rule(
        "ask-rebid",
        "Gerber over a notrump rebid",
        ctx("responder", { partnerLast: NT_OPENING, roundMin: 2, contested: false }),
        all(tp(18), not(any(len("S", 4), len("H", 4)))),
        bid(4, "C"),
        13,
      ),
      rule(
        "r0",
        "0 or 4 aces",
        ctx("any", { ownLast: NT_OPENING, partnerLast: is("4C") }),
        any({ aces: { max: 0 } }, { aces: { min: 4 } }),
        bid(4, "D"),
        14,
      ),
      rule(
        "r1",
        "One ace",
        ctx("any", { ownLast: NT_OPENING, partnerLast: is("4C") }),
        { aces: { min: 1, max: 1 } },
        bid(4, "H"),
        15,
      ),
      rule(
        "r2",
        "Two aces",
        ctx("any", { ownLast: NT_OPENING, partnerLast: is("4C") }),
        { aces: { min: 2, max: 2 } },
        bid(4, "S"),
        16,
      ),
      rule(
        "r3",
        "Three aces",
        ctx("any", { ownLast: NT_OPENING, partnerLast: is("4C") }),
        { aces: { min: 3, max: 3 } },
        bid(4, "N"),
        17,
      ),
      // 5♣ continuation asks for kings (guarantees all the aces).
      rule(
        "k04",
        "0 or 4 kings",
        ctx("any", { ownLast: bidAt({ level: 4 }), partnerLast: is("5C") }),
        any({ kings: { max: 0 } }, { kings: { min: 4 } }),
        bid(5, "D"),
        17,
      ),
      rule(
        "k1",
        "One king",
        ctx("any", { ownLast: bidAt({ level: 4 }), partnerLast: is("5C") }),
        { kings: { min: 1, max: 1 } },
        bid(5, "H"),
        18,
      ),
      rule(
        "k2",
        "Two kings",
        ctx("any", { ownLast: bidAt({ level: 4 }), partnerLast: is("5C") }),
        { kings: { min: 2, max: 2 } },
        bid(5, "S"),
        19,
      ),
      rule(
        "k3",
        "Three kings",
        ctx("any", { ownLast: bidAt({ level: 4 }), partnerLast: is("5C") }),
        { kings: { min: 3, max: 3 } },
        bid(5, "N"),
        20,
      ),
    ],
    { settings: [toggle("gerber_on", "Gerber over notrump")], sets: ["conventions"] },
  ),

  auctionItem(
    "nt-raises",
    "Raises of a notrump opening",
    "Natural ladder over 1NT: 2NT invites with 8–9, 3NT is to play with 10–15, 4NT invites slam quantitatively with 16–17 (opener accepts with a maximum). Over 2NT, 3NT is to play with 5–11.",
    "agreement",
    [
      rule(
        "invite",
        "2NT invitation",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        all(bal(), hcp(8, 9)),
        bid(2, "N"),
        40,
      ),
      rule(
        "game",
        "Raise to 3NT",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        hcp(10, 15),
        bid(3, "N"),
        41,
      ),
      rule(
        "quant",
        "Quantitative 4NT",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        all(bal(), hcp(16, 17)),
        bid(4, "N"),
        42,
      ),
      rule(
        "accept-quant",
        "Accept the quantitative invite",
        ctx("opener", { ownFirst: is("1N"), ownLast: is("1N"), partnerLast: is("4N") }),
        hcp(17),
        bid(6, "N"),
        43,
      ),
      rule(
        "game-2n",
        "Raise 2NT to game",
        ctx("responder", { opening: is("2N"), partnerLast: is("2N"), contested: false }),
        hcp(5, 11),
        bid(3, "N"),
        44,
      ),
    ],
  ),
];
