// Responding to 1NT/2NT (SAYC booklet ch. 2): Stayman with every opener
// reply and responder continuation, Jacoby + Texas transfers with
// completions, super-accepts, continuations and opener's 3NT correction,
// Gerber, and the natural quantitative ladder. The generic continuation
// rules lean on the new auction memory (ownLast/ownFirst/partnerFirst), so
// one rule covers both majors wherever possible.

import {
  all,
  any,
  auctionItem,
  bal,
  bid,
  bidAt,
  ctx,
  hcp,
  is,
  len,
  not,
  pass as passAction,
  raise,
  rule,
  toggle,
  tp,
  type TemplateItem,
} from "../dsl";

const NT_OPENING = bidAt({ max: 2, strains: ["N"] });

export const NT_RESPONSES: TemplateItem[] = [
  auctionItem(
    "stayman",
    "Stayman",
    "Over partner's 1NT (or 2NT), 2♣ (3♣) asks for a four-card major with invitational values or better. Opener shows a major or denies with 2♦; responder places the contract.",
    "convention",
    [
      // The ask.
      rule(
        "ask",
        "Stayman 2♣ ask",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
        all(hcp(8), any(len("S", 4), len("H", 4))),
        bid(2, "C"),
        25,
      ),
      rule(
        "ask2n",
        "Stayman 3♣ over 2NT",
        ctx("responder", { opening: is("2N"), partnerLast: is("2N") }),
        all(hcp(4), any(len("S", 4), len("H", 4))),
        bid(3, "C"),
        26,
      ),
      // Opener's replies (hearts first with both).
      rule(
        "reply-h",
        "Show four hearts",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2C") }),
        len("H", 4),
        bid(2, "H"),
        27,
      ),
      rule(
        "reply-s",
        "Show four spades",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2C") }),
        len("S", 4),
        bid(2, "S"),
        28,
      ),
      rule(
        "reply-d",
        "Deny a four-card major",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2C") }),
        { all: [] },
        bid(2, "D"),
        29,
      ),
      rule(
        "reply-h-2n",
        "Show four hearts (over 2NT)",
        ctx("opener", { ownFirst: is("2N"), partnerLast: is("3C") }),
        len("H", 4),
        bid(3, "H"),
        30,
      ),
      rule(
        "reply-s-2n",
        "Show four spades (over 2NT)",
        ctx("opener", { ownFirst: is("2N"), partnerLast: is("3C") }),
        len("S", 4),
        bid(3, "S"),
        31,
      ),
      rule(
        "reply-d-2n",
        "Deny a major (over 2NT)",
        ctx("opener", { ownFirst: is("2N"), partnerLast: is("3C") }),
        { all: [] },
        bid(3, "D"),
        32,
      ),
      // Responder's continuations after a 2♦ denial.
      rule(
        "cont-2n",
        "Invite after the denial",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: is("2D") }),
        hcp(8, 9),
        bid(2, "N"),
        33,
      ),
      rule(
        "cont-3n",
        "Bid game after the denial",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: is("2D") }),
        hcp(10, 15),
        bid(3, "N"),
        34,
      ),
      // Continuations when opener shows a major.
      rule(
        "cont-raise-inv",
        "Invite with the fit",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: bidAt({ level: 2, strains: ["H", "S"] }) }),
        all(hcp(8, 9), len("partner_last_bid_suit", 4)),
        raise(3),
        35,
      ),
      rule(
        "cont-raise-game",
        "Bid game in the fit",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: bidAt({ level: 2, strains: ["H", "S"] }) }),
        all(hcp(10, 15), len("partner_last_bid_suit", 4)),
        raise(4),
        36,
      ),
      rule(
        "cont-3n-nofit",
        "3NT without the fit",
        ctx("responder", { opening: is("1N"), ownLast: is("2C"), partnerLast: bidAt({ level: 2, strains: ["H", "S"] }) }),
        all(hcp(10, 15), len("partner_last_bid_suit", undefined, 3)),
        bid(3, "N"),
        37,
      ),
    ],
    { settings: [toggle("stayman_on", "Stayman")], sets: ["conventions"] },
  ),

  auctionItem(
    "jacoby-transfers",
    "Jacoby transfers",
    "Over partner's notrump opening, 2♦ shows five-plus hearts and 2♥ shows five-plus spades (3♦/3♥ over 2NT). Opener completes the transfer — jumping with four-card support and a maximum — and responder then passes, invites, or drives to game.",
    "convention",
    [
      rule(
        "xfer-h",
        "Transfer to hearts",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
        len("H", 5),
        bid(2, "D"),
        15,
      ),
      rule(
        "xfer-s",
        "Transfer to spades",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
        len("S", 5),
        bid(2, "H"),
        16,
      ),
      rule(
        "xfer-h-2n",
        "Transfer to hearts (over 2NT)",
        ctx("responder", { opening: is("2N"), partnerLast: is("2N") }),
        len("H", 5),
        bid(3, "D"),
        17,
      ),
      rule(
        "xfer-s-2n",
        "Transfer to spades (over 2NT)",
        ctx("responder", { opening: is("2N"), partnerLast: is("2N") }),
        len("S", 5),
        bid(3, "H"),
        18,
      ),
      // Opener: super-accept with four trumps and a maximum, else complete.
      rule(
        "super-h",
        "Super-accept hearts",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2D") }),
        all(len("H", 4), hcp(17)),
        bid(3, "H"),
        19,
      ),
      rule(
        "super-s",
        "Super-accept spades",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2H") }),
        all(len("S", 4), hcp(17)),
        bid(3, "S"),
        20,
      ),
      rule(
        "complete-h",
        "Complete the hearts transfer",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2D") }),
        { all: [] },
        bid(2, "H"),
        21,
      ),
      rule(
        "complete-s",
        "Complete the spades transfer",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("2H") }),
        { all: [] },
        bid(2, "S"),
        22,
      ),
      rule(
        "complete-h-2n",
        "Complete (over 2NT)",
        ctx("opener", { ownFirst: is("2N"), partnerLast: is("3D") }),
        { all: [] },
        bid(3, "H"),
        23,
      ),
      rule(
        "complete-s-2n",
        "Complete (over 2NT)",
        ctx("opener", { ownFirst: is("2N"), partnerLast: is("3H") }),
        { all: [] },
        bid(3, "S"),
        24,
      ),
      // Responder's continuations (generic across both majors).
      rule(
        "cont-pass",
        "Pass with a weak hand",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        tp(undefined, 8),
        passAction,
        40,
      ),
      rule(
        "cont-invite-nt",
        "Invite with 2NT (five-card suit)",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        all(hcp(8, 9), len("partner_last_bid_suit", undefined, 5)),
        bid(2, "N"),
        41,
      ),
      rule(
        "cont-invite-raise",
        "Invite with the six-card suit",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        all(hcp(8, 9), len("partner_last_bid_suit", 6)),
        raise(3),
        42,
      ),
      rule(
        "cont-game-nt",
        "3NT with five and game values",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        all(hcp(10, 15), len("partner_last_bid_suit", 5, 5)),
        bid(3, "N"),
        43,
      ),
      rule(
        "cont-game-raise",
        "Game with six-plus trumps",
        ctx("responder", {
          opening: is("1N"),
          ownLast: bidAt({ level: 2, strains: ["D", "H"] }),
          partnerLast: bidAt({ level: 2, strains: ["H", "S"] }),
        }),
        all(hcp(10, 15), len("partner_last_bid_suit", 6)),
        raise(4),
        44,
      ),
      // Opener corrects 3NT to four of the major with three-card support.
      rule(
        "correct-h",
        "Correct 3NT to 4♥",
        ctx("opener", { ownFirst: is("1N"), partnerFirst: is("2D"), partnerLast: is("3N") }),
        len("H", 3),
        bid(4, "H"),
        45,
      ),
      rule(
        "correct-s",
        "Correct 3NT to 4♠",
        ctx("opener", { ownFirst: is("1N"), partnerFirst: is("2H"), partnerLast: is("3N") }),
        len("S", 3),
        bid(4, "S"),
        46,
      ),
    ],
    { settings: [toggle("jacoby_on", "Jacoby transfers")], sets: ["conventions"] },
  ),

  auctionItem(
    "texas-transfers",
    "Texas transfers",
    "Over 1NT with a six-card major and game values, 4♦ transfers to 4♥ and 4♥ transfers to 4♠.",
    "convention",
    [
      rule(
        "tx-h",
        "Texas transfer to hearts",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
        all(len("H", 6), hcp(10, 15)),
        bid(4, "D"),
        13,
      ),
      rule(
        "tx-s",
        "Texas transfer to spades",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N") }),
        all(len("S", 6), hcp(10, 15)),
        bid(4, "H"),
        14,
      ),
      rule(
        "tx-complete-h",
        "Complete to 4♥",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("4D") }),
        { all: [] },
        bid(4, "H"),
        15,
      ),
      rule(
        "tx-complete-s",
        "Complete to 4♠",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("4H") }),
        { all: [] },
        bid(4, "S"),
        16,
      ),
    ],
    { settings: [toggle("texas_on", "Texas transfers")], sets: ["conventions"] },
  ),

  auctionItem(
    "gerber",
    "Gerber over notrump",
    "Over partner's notrump opening, 4♣ asks for aces with slam interest: 4♦ shows 0 or 4, 4♥ one, 4♠ two, 4NT three.",
    "convention",
    [
      rule(
        "ask",
        "Gerber 4♣ ask",
        ctx("responder", { opening: NT_OPENING, partnerLast: NT_OPENING }),
        all(tp(18), not(any(len("S", 4), len("H", 4)))),
        bid(4, "C"),
        12,
      ),
      rule(
        "r0",
        "0 or 4 aces",
        ctx("opener", { ownFirst: NT_OPENING, partnerLast: is("4C") }),
        any({ aces: { max: 0 } }, { aces: { min: 4 } }),
        bid(4, "D"),
        13,
      ),
      rule(
        "r1",
        "One ace",
        ctx("opener", { ownFirst: NT_OPENING, partnerLast: is("4C") }),
        { aces: { min: 1, max: 1 } },
        bid(4, "H"),
        14,
      ),
      rule(
        "r2",
        "Two aces",
        ctx("opener", { ownFirst: NT_OPENING, partnerLast: is("4C") }),
        { aces: { min: 2, max: 2 } },
        bid(4, "S"),
        15,
      ),
      rule(
        "r3",
        "Three aces",
        ctx("opener", { ownFirst: NT_OPENING, partnerLast: is("4C") }),
        { aces: { min: 3, max: 3 } },
        bid(4, "N"),
        16,
      ),
    ],
    { settings: [toggle("gerber_on", "Gerber over notrump")], sets: ["conventions"] },
  ),

  auctionItem(
    "nt-raises",
    "Raises of a notrump opening",
    "Natural ladder over 1NT: 2NT invites with 8–9, 3NT is to play with 10–15, 4NT invites slam quantitatively with 16–17 (opener accepts with a maximum). Over 2NT, 3NT is to play with 5–11.",
    "agreement",
    [
      rule(
        "invite",
        "2NT invitation",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        all(bal(), hcp(8, 9)),
        bid(2, "N"),
        40,
      ),
      rule(
        "game",
        "Raise to 3NT",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        hcp(10, 15),
        bid(3, "N"),
        41,
      ),
      rule(
        "quant",
        "Quantitative 4NT",
        ctx("responder", { opening: is("1N"), partnerLast: is("1N"), contested: false }),
        all(bal(), hcp(16, 17)),
        bid(4, "N"),
        42,
      ),
      rule(
        "accept-quant",
        "Accept the quantitative invite",
        ctx("opener", { ownFirst: is("1N"), partnerLast: is("4N") }),
        hcp(17),
        bid(6, "N"),
        43,
      ),
      rule(
        "game-2n",
        "Raise 2NT to game",
        ctx("responder", { opening: is("2N"), partnerLast: is("2N"), contested: false }),
        hcp(5, 11),
        bid(3, "N"),
        44,
      ),
    ],
  ),
];
