// Rebids (SAYC booklet ch. 5–6): opener's second call by strength and shape,
// responder's second call, New Minor Forcing, and the strong 2♣ machinery.
// These are the sequences extraction never made executable — the multi-round
// auction memory (ownFirst/partnerFirst/ownLast) carries them.

import {
  all,
  any,
  auctionItem,
  bal,
  bid,
  bidAt,
  bidSuit,
  ctx,
  hcp,
  is,
  len,
  pass as passAction,
  raise,
  rule,
  toggle,
  tp,
  type TemplateItem,
} from "../dsl";

const SUIT_OPENING = bidAt({ level: 1, strains: ["C", "D", "H", "S"] });
const ONE_LEVEL_RESPONSE = bidAt({ level: 1 });

export const REBIDS: TemplateItem[] = [
  auctionItem(
    "opener-rebids",
    "Opener's rebids",
    "Opener's second call follows the booklet ladder. Minimum (13–15): cheapest notrump, single raise, a new suit without reversing, or the cheapest rebid of the opening suit. Medium (16–18): jump raise, jump rebid, or a REVERSE (a new suit at the two level higher-ranking than the opening suit). Maximum (19–21): jump in notrump, double-jump raise, or a jump shift.",
    "agreement",
    [
      rule(
        "raise-double-jump",
        "Double-jump raise (maximum)",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2 }),
        all(len("partner_last_bid_suit", 4), tp(19, 21)),
        raise(4),
        29,
      ),
      rule(
        "raise-min",
        "Raise partner's suit (minimum)",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2 }),
        all(len("partner_last_bid_suit", 4), tp(13, 15)),
        raise(2),
        30,
      ),
      rule(
        "raise-jump",
        "Jump raise with extras",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2 }),
        all(len("partner_last_bid_suit", 4), tp(16, 18)),
        raise(3),
        31,
      ),
      rule(
        "rebid-1nt",
        "1NT rebid (12–14 balanced)",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2 }),
        all(bal(), hcp(12, 14)),
        bid(1, "N"),
        32,
      ),
      rule(
        "rebid-2nt",
        "Jump 2NT rebid (18–19 balanced)",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2 }),
        all(bal(), hcp(18, 19)),
        bid(2, "N"),
        33,
      ),
      rule(
        "rebid-suit",
        "Rebid a six-card suit",
        ctx("opener", { ownFirst: SUIT_OPENING, roundMin: 2, contested: false }),
        all(len("own_first_bid_suit", 6), tp(13, 15)),
        bidSuit("own_first_bid_suit", 2),
        34,
      ),
      rule(
        "rebid-suit-jump",
        "Jump rebid with a strong six-card suit",
        ctx("opener", { ownFirst: SUIT_OPENING, roundMin: 2, contested: false }),
        all(len("own_first_bid_suit", 6), tp(16, 18)),
        bidSuit("own_first_bid_suit", 3),
        35,
      ),
      // New suit WITHOUT reversing: the one level first…
      rule(
        "second-suit-1",
        "New suit at the one level",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2, contested: false }),
        all(tp(12, 18), any(len("D", 4), len("H", 4), len("S", 4))),
        { type: "bid_longest", among: ["D", "H", "S"], level: 1 },
        36,
      ),
      // …then two-level suits LOWER-ranking than the opening (not a reverse).
      rule(
        "second-suit-2-after-1s",
        "Lower-ranking second suit (after 1♠)",
        ctx("opener", { ownFirst: is("1S"), roundMin: 2, contested: false }),
        all(tp(12, 18), any(len("C", 4), len("H", 4), len("D", 4))),
        { type: "bid_longest", among: ["C", "D", "H"], level: 2 },
        37,
      ),
      rule(
        "second-suit-2-after-1h",
        "Lower-ranking second suit (after 1♥)",
        ctx("opener", { ownFirst: is("1H"), roundMin: 2, contested: false }),
        all(tp(12, 18), any(len("C", 4), len("D", 4))),
        { type: "bid_longest", among: ["C", "D"], level: 2 },
        38,
      ),
      rule(
        "second-suit-2-after-1d",
        "2♣ second suit (after 1♦)",
        ctx("opener", { ownFirst: is("1D"), roundMin: 2, contested: false }),
        all(tp(12, 18), len("C", 4)),
        bid(2, "C"),
        39,
      ),
    ],
  ),

  auctionItem(
    "reverses",
    "Reverses by opener",
    "A new suit at the two level HIGHER-ranking than the opening suit is a reverse: 16–18+ points, forcing for one round (with a jump shift it forces game). 1♣–1♠–2♥ and 1♦–1♠–2♥ are reverses; 2♣ over anything is not.",
    "agreement",
    [
      rule(
        "rev-1c-2d",
        "Reverse into diamonds",
        ctx("opener", { ownFirst: is("1C"), partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2, contested: false }),
        all(tp(17, 21), len("D", 4)),
        bid(2, "D"),
        33,
      ),
      rule(
        "rev-2h",
        "Reverse into hearts",
        ctx("opener", { ownFirst: bidAt({ level: 1, strains: ["C", "D"] }), partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2, contested: false }),
        all(tp(17, 21), len("H", 4)),
        bid(2, "H"),
        34,
      ),
      rule(
        "rev-2s",
        "Reverse into spades",
        ctx("opener", { ownFirst: bidAt({ level: 1, strains: ["C", "D", "H"] }), partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2, contested: false }),
        all(tp(17, 21), len("S", 4)),
        bid(2, "S"),
        35,
      ),
    ],
  ),

  auctionItem(
    "responder-rebids",
    "Responder's rebids",
    "Responder's second call (booklet framework): sign off in a partscore (pass, 1NT, two of a bid suit), invite with 2NT or three of a bid suit (10–11), or sign off in game. After a TWO-level first response, responder promises another bid below game, and a jump raise of opener's first suit to the three level is game forcing. After opener's 1NT rebid, a new suit is non-forcing; only a jump shift or reverse forces.",
    "agreement",
    [
      rule(
        "invite-nt",
        "Invite over the 1NT rebid",
        ctx("responder", { partnerLast: is("1N"), roundMin: 2, contested: false }),
        all(bal(), hcp(11, 12)),
        bid(2, "N"),
        30,
      ),
      rule(
        "game-nt",
        "3NT over the 1NT rebid",
        ctx("responder", { partnerLast: is("1N"), roundMin: 2, contested: false }),
        all(hcp(13, 17)),
        bid(3, "N"),
        31,
      ),
      rule(
        "raise-game",
        "Raise partner's second suit to game",
        ctx("responder", { partnerLast: bidAt({ min: 2, max: 3, strains: ["H", "S"] }), roundMin: 2 }),
        all(len("partner_last_bid_suit", 4), tp(13)),
        raise(4),
        32,
      ),
      rule(
        "invite-raise-second",
        "Invite in opener's second suit",
        ctx("responder", { partnerLast: bidAt({ level: 2 }), partnerFirst: bidAt({ level: 1, strains: ["C", "D", "H", "S"] }), roundMin: 2, contested: false }),
        all(len("partner_last_bid_suit", 4), tp(10, 12)),
        raise(3),
        33,
      ),
      rule(
        "gf-raise-first",
        "Jump raise of opener's first suit (game force)",
        ctx("responder", { ownFirst: bidAt({ level: 2 }), partnerFirst: bidAt({ level: 1, strains: ["C", "D", "H", "S"] }), roundMin: 2, contested: false }),
        all(len("partner_first_bid_suit", 3), tp(13)),
        bidSuit("partner_first_bid_suit", 3),
        34,
      ),
      rule(
        "invite-nt-generic",
        "2NT invitation on the second round",
        ctx("responder", { partnerLast: bidAt({ max: 2 }), roundMin: 2, contested: false }),
        all(bal(), tp(10, 12)),
        bid(2, "N"),
        35,
      ),
      rule(
        "rebid-own-weak",
        "Rebid a six-card suit (sign-off)",
        ctx("responder", { partnerLast: is("1N"), ownFirst: bidAt({ level: 1 }), roundMin: 2, contested: false }),
        all(len("own_first_bid_suit", 6), tp(undefined, 9)),
        bidSuit("own_first_bid_suit", 2),
        36,
      ),
      rule(
        "jump-own-gf",
        "Jump rebid of responder's suit (game force after 1NT)",
        ctx("responder", { partnerLast: is("1N"), ownFirst: bidAt({ level: 1 }), roundMin: 2, contested: false }),
        all(len("own_first_bid_suit", 6), tp(13)),
        bidSuit("own_first_bid_suit", 3),
        37,
      ),
      rule(
        "preference",
        "Give preference to opener's first suit",
        ctx("responder", { partnerLast: bidAt({ level: 2 }), partnerFirst: bidAt({ level: 1, strains: ["C", "D", "H", "S"] }), roundMin: 2, contested: false }),
        all(tp(6, 9), len("partner_first_bid_suit", 2)),
        bidSuit("partner_first_bid_suit", 2),
        50,
      ),
      rule(
        "pass-min",
        "Pass a minimum",
        ctx("responder", { partnerLast: bidAt({ max: 2 }), roundMin: 2, contested: false }),
        tp(undefined, 9),
        passAction,
        90,
      ),
    ],
  ),

  auctionItem(
    "new-minor-forcing",
    "New Minor Forcing",
    "After 1♣/1♦ – 1♥/1♠ – 1NT, a bid of the other minor by responder is artificial and forcing, asking for three-card support for the major (11+ points, usually a five-card major). Opener shows support at the two level with a minimum or the three level with a maximum.",
    "convention",
    [
      rule(
        "ask-after-1c",
        "NMF 2♦ (after a 1♣ opening)",
        ctx("responder", {
          opening: is("1C"),
          ownFirst: bidAt({ level: 1, strains: ["H", "S"] }),
          partnerLast: is("1N"),
        }),
        all(tp(11), len("own_first_bid_suit", 5)),
        bid(2, "D"),
        20,
      ),
      rule(
        "ask-after-1d",
        "NMF 2♣ (after a 1♦ opening)",
        ctx("responder", {
          opening: is("1D"),
          ownFirst: bidAt({ level: 1, strains: ["H", "S"] }),
          partnerLast: is("1N"),
        }),
        all(tp(11), len("own_first_bid_suit", 5)),
        bid(2, "C"),
        21,
      ),
      rule(
        "show-support-max",
        "Show support with a maximum",
        ctx("opener", {
          ownLast: is("1N"),
          partnerLast: bidAt({ level: 2, strains: ["C", "D"] }),
          partnerFirst: bidAt({ level: 1, strains: ["H", "S"] }),
        }),
        all(len("partner_first_bid_suit", 3), hcp(13, 14)),
        bidSuit("partner_first_bid_suit", 3),
        22,
      ),
      rule(
        "show-support",
        "Show three-card support",
        ctx("opener", {
          ownLast: is("1N"),
          partnerLast: bidAt({ level: 2, strains: ["C", "D"] }),
          partnerFirst: bidAt({ level: 1, strains: ["H", "S"] }),
        }),
        len("partner_first_bid_suit", 3),
        bidSuit("partner_first_bid_suit", 2),
        23,
      ),
      rule(
        "deny-support",
        "Deny support (2NT)",
        ctx("opener", {
          ownLast: is("1N"),
          partnerLast: bidAt({ level: 2, strains: ["C", "D"] }),
          partnerFirst: bidAt({ level: 1, strains: ["H", "S"] }),
        }),
        { all: [] },
        bid(2, "N"),
        24,
      ),
    ],
    { settings: [toggle("nmf_on", "New Minor Forcing")], sets: ["conventions"] },
  ),

  auctionItem(
    "strong-2c-machinery",
    "After the strong 2♣",
    "Responder bids 2♦ as an artificial waiting bid (a positive 2♥/2♠ shows a good five-card suit and 8+). Opener then shows the hand naturally: 2NT with 22–24 balanced, else the long suit.",
    "convention",
    [
      rule(
        "positive-major",
        "Positive response",
        ctx("responder", { opening: is("2C"), partnerLast: is("2C") }),
        all(hcp(8), any(len("S", 5), len("H", 5)), { suitQuality: { suit: "own_longest_suit", quality: "two_of_top_three" } }),
        { type: "bid_longest", among: ["S", "H"], level: 2 },
        29,
      ),
      rule(
        "positive-nt",
        "2NT positive response (balanced 8+)",
        ctx("responder", { opening: is("2C"), partnerLast: is("2C") }),
        all(bal(), hcp(8)),
        bid(2, "N"),
        30,
      ),
      rule(
        "waiting",
        "2♦ waiting",
        ctx("responder", { opening: is("2C"), partnerLast: is("2C") }),
        { all: [] },
        bid(2, "D"),
        31,
      ),
      rule(
        "rebid-nt",
        "2NT rebid (22–24 balanced)",
        ctx("opener", { ownFirst: is("2C"), partnerLast: is("2D") }),
        bal(),
        bid(2, "N"),
        32,
      ),
      rule(
        "rebid-suit",
        "Show the long suit",
        ctx("opener", { ownFirst: is("2C"), partnerLast: is("2D") }),
        { all: [] },
        { type: "bid_longest", among: ["S", "H", "D", "C"] },
        33,
      ),
      rule(
        "second-response",
        "Responder raises opener's suit",
        ctx("responder", { opening: is("2C"), partnerLast: bidAt({ min: 2, max: 3, strains: ["S", "H", "D", "C"] }), roundMin: 3 }),
        len("partner_last_bid_suit", 3),
        raise(4),
        34,
      ),
      rule(
        "second-nt",
        "Responder raises 2NT to game",
        ctx("responder", { opening: is("2C"), partnerLast: is("2N"), roundMin: 3 }),
        hcp(3),
        bid(3, "N"),
        35,
      ),
    ],
    { settings: [toggle("strong2c_responses_on", "2♦ waiting over the strong 2♣")], sets: ["conventions"] },
  ),
];
