// Rebids (SAYC booklet ch. 5–6): opener's second call by strength and shape,
// responder's second call, New Minor Forcing, and the strong 2♣ machinery.
// These are the sequences extraction never made executable — the multi-round
// auction memory (ownFirst/partnerFirst/ownLast) carries them.

import {
  all,
  any,
  auctionItem,
  bal,
  bid,
  bidAt,
  bidSuit,
  ctx,
  hcp,
  is,
  len,
  pass as passAction,
  raise,
  rule,
  toggle,
  tp,
  type TemplateItem,
} from "../dsl";

const SUIT_OPENING = bidAt({ level: 1, strains: ["C", "D", "H", "S"] });
const ONE_LEVEL_RESPONSE = bidAt({ level: 1 });

export const REBIDS: TemplateItem[] = [
  auctionItem(
    "opener-rebids",
    "Opener's rebids",
    "After a one-of-a-suit opening and partner's response: rebid 1NT balanced with a minimum (12–14), jump to 2NT with 18–19, raise partner's suit with four-card support (single with a minimum, jump with extras), or rebid a six-card suit.",
    "agreement",
    [
      rule(
        "raise-min",
        "Raise partner's suit (minimum)",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2 }),
        all(len("partner_last_bid_suit", 4), tp(13, 15)),
        raise(2),
        30,
      ),
      rule(
        "raise-jump",
        "Jump raise with extras",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2 }),
        all(len("partner_last_bid_suit", 4), tp(16, 18)),
        raise(3),
        31,
      ),
      rule(
        "rebid-1nt",
        "1NT rebid (12–14 balanced)",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2 }),
        all(bal(), hcp(12, 14)),
        bid(1, "N"),
        32,
      ),
      rule(
        "rebid-2nt",
        "Jump 2NT rebid (18–19 balanced)",
        ctx("opener", { ownFirst: SUIT_OPENING, partnerLast: ONE_LEVEL_RESPONSE, roundMin: 2 }),
        all(bal(), hcp(18, 19)),
        bid(2, "N"),
        33,
      ),
      rule(
        "rebid-suit",
        "Rebid a six-card suit",
        ctx("opener", { ownFirst: SUIT_OPENING, roundMin: 2, contested: false }),
        all(len("own_first_bid_suit", 6), tp(13, 15)),
        bidSuit("own_first_bid_suit", 2),
        34,
      ),
      rule(
        "rebid-suit-jump",
        "Jump rebid with a strong six-card suit",
        ctx("opener", { ownFirst: SUIT_OPENING, roundMin: 2, contested: false }),
        all(len("own_first_bid_suit", 6), tp(16, 18)),
        bidSuit("own_first_bid_suit", 3),
        35,
      ),
    ],
  ),

  auctionItem(
    "responder-rebids",
    "Responder's rebids",
    "Responder's second call: pass a minimum, invite with 11–12 over opener's 1NT rebid, drive to 3NT with 13+, or take the partnership back to opener's major with a doubleton and a weak hand.",
    "agreement",
    [
      rule(
        "invite-nt",
        "Invite over the 1NT rebid",
        ctx("responder", { partnerLast: is("1N"), roundMin: 2, contested: false }),
        all(bal(), hcp(11, 12)),
        bid(2, "N"),
        30,
      ),
      rule(
        "game-nt",
        "3NT over the 1NT rebid",
        ctx("responder", { partnerLast: is("1N"), roundMin: 2, contested: false }),
        all(hcp(13, 17)),
        bid(3, "N"),
        31,
      ),
      rule(
        "raise-game",
        "Raise partner's second suit to game",
        ctx("responder", { partnerLast: bidAt({ min: 2, max: 3, strains: ["H", "S"] }), roundMin: 2 }),
        all(len("partner_last_bid_suit", 4), tp(13)),
        raise(4),
        32,
      ),
      rule(
        "preference",
        "Give preference to opener's first suit",
        ctx("responder", { partnerLast: bidAt({ level: 2 }), partnerFirst: bidAt({ level: 1, strains: ["C", "D", "H", "S"] }), roundMin: 2, contested: false }),
        all(tp(6, 9), len("partner_first_bid_suit", 2)),
        bidSuit("partner_first_bid_suit", 2),
        50,
      ),
      rule(
        "pass-min",
        "Pass a minimum",
        ctx("responder", { partnerLast: bidAt({ max: 2 }), roundMin: 2, contested: false }),
        tp(undefined, 9),
        passAction,
        90,
      ),
    ],
  ),

  auctionItem(
    "new-minor-forcing",
    "New Minor Forcing",
    "After 1♣/1♦ – 1♥/1♠ – 1NT, a bid of the other minor by responder is artificial and forcing, asking for three-card support for the major (11+ points, usually a five-card major). Opener shows support at the two level with a minimum or the three level with a maximum.",
    "convention",
    [
      rule(
        "ask-after-1c",
        "NMF 2♦ (after a 1♣ opening)",
        ctx("responder", {
          opening: is("1C"),
          ownFirst: bidAt({ level: 1, strains: ["H", "S"] }),
          partnerLast: is("1N"),
        }),
        all(tp(11), len("own_first_bid_suit", 5)),
        bid(2, "D"),
        20,
      ),
      rule(
        "ask-after-1d",
        "NMF 2♣ (after a 1♦ opening)",
        ctx("responder", {
          opening: is("1D"),
          ownFirst: bidAt({ level: 1, strains: ["H", "S"] }),
          partnerLast: is("1N"),
        }),
        all(tp(11), len("own_first_bid_suit", 5)),
        bid(2, "C"),
        21,
      ),
      rule(
        "show-support-max",
        "Show support with a maximum",
        ctx("opener", {
          ownLast: is("1N"),
          partnerLast: bidAt({ level: 2, strains: ["C", "D"] }),
          partnerFirst: bidAt({ level: 1, strains: ["H", "S"] }),
        }),
        all(len("partner_first_bid_suit", 3), hcp(13, 14)),
        bidSuit("partner_first_bid_suit", 3),
        22,
      ),
      rule(
        "show-support",
        "Show three-card support",
        ctx("opener", {
          ownLast: is("1N"),
          partnerLast: bidAt({ level: 2, strains: ["C", "D"] }),
          partnerFirst: bidAt({ level: 1, strains: ["H", "S"] }),
        }),
        len("partner_first_bid_suit", 3),
        bidSuit("partner_first_bid_suit", 2),
        23,
      ),
      rule(
        "deny-support",
        "Deny support (2NT)",
        ctx("opener", {
          ownLast: is("1N"),
          partnerLast: bidAt({ level: 2, strains: ["C", "D"] }),
          partnerFirst: bidAt({ level: 1, strains: ["H", "S"] }),
        }),
        { all: [] },
        bid(2, "N"),
        24,
      ),
    ],
    { settings: [toggle("nmf_on", "New Minor Forcing")], sets: ["conventions"] },
  ),

  auctionItem(
    "strong-2c-machinery",
    "After the strong 2♣",
    "Responder bids 2♦ as an artificial waiting bid (a positive 2♥/2♠ shows a good five-card suit and 8+). Opener then shows the hand naturally: 2NT with 22–24 balanced, else the long suit.",
    "convention",
    [
      rule(
        "positive-major",
        "Positive response",
        ctx("responder", { opening: is("2C"), partnerLast: is("2C") }),
        all(hcp(8), any(len("S", 5), len("H", 5)), { suitQuality: { suit: "own_longest_suit", quality: "two_of_top_three" } }),
        { type: "bid_longest", among: ["S", "H"], level: 2 },
        29,
      ),
      rule(
        "positive-nt",
        "2NT positive response (balanced 8+)",
        ctx("responder", { opening: is("2C"), partnerLast: is("2C") }),
        all(bal(), hcp(8)),
        bid(2, "N"),
        30,
      ),
      rule(
        "waiting",
        "2♦ waiting",
        ctx("responder", { opening: is("2C"), partnerLast: is("2C") }),
        { all: [] },
        bid(2, "D"),
        31,
      ),
      rule(
        "rebid-nt",
        "2NT rebid (22–24 balanced)",
        ctx("opener", { ownFirst: is("2C"), partnerLast: is("2D") }),
        bal(),
        bid(2, "N"),
        32,
      ),
      rule(
        "rebid-suit",
        "Show the long suit",
        ctx("opener", { ownFirst: is("2C"), partnerLast: is("2D") }),
        { all: [] },
        { type: "bid_longest", among: ["S", "H", "D", "C"] },
        33,
      ),
      rule(
        "second-response",
        "Responder raises opener's suit",
        ctx("responder", { opening: is("2C"), partnerLast: bidAt({ min: 2, max: 3, strains: ["S", "H", "D", "C"] }), roundMin: 3 }),
        len("partner_last_bid_suit", 3),
        raise(4),
        34,
      ),
      rule(
        "second-nt",
        "Responder raises 2NT to game",
        ctx("responder", { opening: is("2C"), partnerLast: is("2N"), roundMin: 3 }),
        hcp(3),
        bid(3, "N"),
        35,
      ),
    ],
    { settings: [toggle("strong2c_responses_on", "2♦ waiting over the strong 2♣")], sets: ["conventions"] },
  ),
];
