-- Bridge taxonomy seed — reference vocabulary mirrored from @bridge/taxonomy.
-- PROVENANCE: verbatim upserts from Applications/BridgePlatform/db/migrations/0009_taxonomy.sql.
-- Idempotent (on conflict do update); re-run on taxonomy changes.

insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_hand_evaluation', 'bidding', 'Hand evaluation (HCP)', 'new') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_opening_bid_selection', 'bidding', 'Opening bid selection', 'new') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_response_selection', 'bidding', 'Response selection', 'new') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_opener_rebid', 'bidding', 'Opener rebid', 'beginner') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_responder_rebid', 'bidding', 'Responder rebid', 'beginner') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_notrump_ranges', 'bidding', 'Notrump ranges', 'beginner') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_major_suit_raises', 'bidding', 'Major suit raises', 'new') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_minor_suit_handling', 'bidding', 'Minor suit handling', 'beginner') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_competitive_bidding', 'bidding', 'Competitive bidding', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_preempts', 'bidding', 'Preempts', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_slam_exploration', 'bidding', 'Slam exploration', 'advanced') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_convention_recognition', 'bidding', 'Convention recognition', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_counting_winners_losers', 'play', 'Counting winners/losers', 'beginner') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_declarer_planning', 'play', 'Declarer planning', 'beginner') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_following_suit', 'play', 'Following suit / legal play', 'new') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_establishing_suits', 'play', 'Establishing suits', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_finesses', 'play', 'Finesses', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_ruffing_losers', 'play', 'Ruffing losers', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_entry_management', 'play', 'Entry management', 'advanced') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_opening_leads', 'defense', 'Opening leads', 'new') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_second_hand_play', 'defense', 'Second hand play', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_third_hand_play', 'defense', 'Third hand play', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_signals', 'defense', 'Signals', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_count_attitude', 'defense', 'Count/attitude', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_defensive_inferences', 'defense', 'Defensive inferences', 'advanced') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_sayc_basics', 'system_familiarity', 'SAYC basics', 'beginner') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_two_over_one_basics', 'system_familiarity', '2/1 basics', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_stayman', 'system_familiarity', 'Stayman', 'beginner') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_transfers', 'system_familiarity', 'Transfers', 'beginner') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_weak_twos', 'system_familiarity', 'Weak twos', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_doubles', 'system_familiarity', 'Doubles', 'intermediate') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_skill_taxonomy (skill_id, category, name, level_band) values ('sk_cue_bids', 'system_familiarity', 'Cue bids', 'advanced') on conflict (skill_id) do update set category = excluded.category, name = excluded.name, level_band = excluded.level_band;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn_opening_bids', 'Opening bids (natural)', '["sk_hand_evaluation","sk_opening_bid_selection"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn_responses', 'Responding to partner''s opening', '["sk_response_selection","sk_major_suit_raises"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn_opener_rebids', 'Opener''s rebid', '["sk_opener_rebid"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn_responder_rebids', 'Responder''s rebid', '["sk_responder_rebid"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn2_nt_opening', '1NT opening and responses', '["sk_notrump_ranges","sk_hand_evaluation"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn2_stayman', 'Stayman over 1NT', '["sk_stayman","sk_convention_recognition"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn2_transfers', 'Jacoby transfers', '["sk_transfers","sk_convention_recognition"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn2_weak_twos', 'Weak two openings', '["sk_weak_twos","sk_preempts"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn2_overcalls', 'Overcalls and takeout doubles', '["sk_competitive_bidding","sk_doubles"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn_opening_leads', 'Opening leads', '["sk_opening_leads"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn_declarer_basics', 'Declarer play basics', '["sk_counting_winners_losers","sk_declarer_planning","sk_following_suit"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
insert into bridge_concept_taxonomy (concept_id, name, related_skill_ids) values ('bn_defense_basics', 'Defense basics', '["sk_second_hand_play","sk_third_hand_play","sk_signals"]'::jsonb) on conflict (concept_id) do update set name = excluded.name, related_skill_ids = excluded.related_skill_ids;
